version: 2.1

jobs:
  test:
    docker:
      - image: cypress/base:ubuntu18-node12.14.1
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key:
            dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key:
            dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
            - /root/.cache
      - run:
          name: create env.js
          command:
            echo "window.API_URL='$API_URL'; window.GITHUB_COMMIT='$COMMIT_REF';
            window.GITHUB_REPO_URL='$REPOSITORY_URL';
            window.GITHUB_USER='$GITHUB_USER'; window.DEPLOY_ID='$DEPLOY_ID';
            window.DEPLOY_URL='$DEPLOY_URL';" > public/env.js
      - run:
          name: test
          command: yarn test:all

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
